version: "3.7"

services:
  geth:
    container_name: geth_ropsten
    restart: unless-stopped
    image: ethereum/client-go:v1.10.18
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8545:8545
    # - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ${DIR}/testnet/geth:/home/geth
    command: >
      --ropsten
      --datadir /home/geth 
      --http 
      --http.addr "0.0.0.0" 
      --http.vhosts "*"
      --http.corsdomain "*" 
      --ws 
      --ws.addr "0.0.0.0" 
      --ws.origins "*"
      --cache=8192
      --maxpeers=200
      --syncmode=snap
      --gpo.percentile=75
      --override.terminaltotaldifficulty "100000000000000000000000"
    networks:
      infura:
        ipv4_address: 10.2.0.101

  bitcoind:
    container_name: bitcoind_testnet
    restart: unless-stopped
    image: kylemanna/bitcoind@sha256:e519bb36398c816fb2905e832bdfc316aa660e9025eac3692151f4f30b5e9c51
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 18332:18332
      - 18333:18333
    volumes:
      - ${DIR}/testnet/bitcoind:/bitcoin/.bitcoin
    command: >
      -rpcbind=0.0.0.0 
      -rpcallowip=0.0.0.0/0 
      -minrelaytxfee=0 
      -maxmempool=300 
      -mempoolexpiry=12 
      -rpcworkqueue=700
      -txindex=1
      -rpcuser=bitcoinrpc
      -rpcpassword=80vDUBXVMS4zH4Z+KjmBQuhKefsh0qNrBvM4G+ry0/48
      -testnet=1
    networks:
      infura:
        ipv4_address: 10.2.0.102

  bsc:
    container_name: bsc_testnet
    restart: unless-stopped
    image: swingbylabs/bsc:1.1.2
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8575:8575
   #  - 8576:8576
      - 30311:30311
      - 30311:30311/udp
    volumes:
      - ${DIR}/testnet/bsc_testnet:/home/geth
    command: >
      --config /home/geth/config.toml
      --datadir /home/geth/data
      --syncmode=snap
      --http 
      --http.addr "0.0.0.0"
      --http.corsdomain "*" 
      --http.port "8575"
      --http.vhosts "*"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port "8576" 
      --ws.origins "0.0.0.0"
    networks:
      infura:
        ipv4_address: 10.2.0.103

  bb_btc:
    container_name: bb_btc_testnet
    restart: unless-stopped
    build: ../../blockbooks/bitcoin/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/testnet/bb_bitcoin:/opt/coins/blockbook/bitcoin_testnet/data
    networks:
      infura:
        ipv4_address: 10.2.0.111

  bb_eth:
    container_name: bb_eth_testnet
    restart: unless-stopped
    build: ../../blockbooks/ethereum/ropsten
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9031:9030
      - 9131:9130
    volumes:
      - ${DIR}/testnet/bb_eth:/opt/coins/blockbook/ethereum_testnet_ropsten/data
    networks:
      infura:
        ipv4_address: 10.2.0.112

  bb_bsc:
    container_name: bb_bsc_testnet
    restart: unless-stopped
    build: ../../blockbooks/bsc/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9032:9030
      - 9132:9130
    volumes:
      - ${DIR}/testnet/bb_bsc:/server/coins/blockbook/bsc_testnet/data
    networks:
      infura:
        ipv4_address: 10.2.0.113

networks:
  infura:
    name: infura
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
