version: "3.7"

services:
  prysm:
    container_name: prysm
    restart: unless-stopped
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.4
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 4000:4000
      - 13000:13000
      - 12000:12000/udp
    volumes:
      - ${DIR}/mainnet/eth2:/data
    command: >
      --accept-terms-of-use
      --datadir=/data
      --jwt-secret=/data/jwtsecret
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --monitoring-host=0.0.0.0
      --execution-endpoint=http://10.2.0.101:8551
      --checkpoint-sync-url=https://mainnet-checkpoint-sync.stakely.io
      --genesis-beacon-api-url=https://mainnet-checkpoint-sync.stakely.io
    networks:
      infura:
        ipv4_address: 10.2.0.104
      
  geth:
    container_name: geth
    restart: unless-stopped
    image: ethereum/client-go:v1.11.5
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8545:8545
    # - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ${DIR}/mainnet/geth:/home/geth
    command: >
      --datadir /home/geth 
      --http 
      --http.addr "0.0.0.0" 
      --http.vhosts "*"
      --authrpc.jwtsecret /home/geth/geth/jwtsecret 
      --authrpc.addr "0.0.0.0" 
      --authrpc.port "8551" 
      --authrpc.vhosts "*"
      --ws 
      --ws.addr "0.0.0.0" 
      --http.corsdomain "*" 
      --ws.origins "*" 
      --cache=4096
      --maxpeers=200
      --syncmode=snap
      --gpo.percentile=75
    networks:
      infura:
        ipv4_address: 10.2.0.101

  bitcoind:
    container_name: bitcoind
    restart: unless-stopped
    image: kylemanna/bitcoind@sha256:17c7dd21690f3be34630db7389d2f0bff14649e27a964afef03806a6d631e0f1
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 8332:8332
      - 8333:8333
    volumes:
      - ${DIR}/mainnet/bitcoind/.bitcoin:/bitcoin/.bitcoin
    command: >
      -rpcbind=0.0.0.0 
      -rpcallowip=0.0.0.0/0 
      -minrelaytxfee=0 
      -maxmempool=300 
      -mempoolexpiry=12 
      -rpcworkqueue=600
      -txindex=1
      -rpcuser=bitcoinrpc
      -rpcpassword=80vDUBXVMS4zH4Z+KjmBQuhKefsh0qNrBvM4G+ry0/48
    networks:
      infura:
        ipv4_address: 10.2.0.102

  bsc:
    container_name: bsc
    restart: unless-stopped
    image: swingbylabs/bsc:1.1.8
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8575:8575
    # - 8576:8576
      - 30311:30311
      - 30311:30311/udp
    volumes:
      - ${DIR}/mainnet/bsc:/home/geth
    command: >
      --config /home/geth/config.toml
      --datadir /home/geth/data
      --syncmode=snap
      --cache 8096
      --txlookuplimit 1600000
      --http 
      --http.addr "0.0.0.0"
      --http.corsdomain "*" 
      --http.port "8575"
      --http.vhosts "*"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port "8576" 
      --ws.origins "0.0.0.0"
      --diffsync
    networks:
      infura:
        ipv4_address: 10.2.0.103

  bb_btc:
    container_name: bb_btc_mainnet
    restart: unless-stopped
    build: ../../blockbooks/bitcoin/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
     #- 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/mainnet/bb_bitcoin:/opt/coins/blockbook/bitcoin/data
    networks:
      infura:
        ipv4_address: 10.2.0.111

  bb_eth:
    container_name: bb_eth_mainnet
    restart: unless-stopped
    build: ../../blockbooks/ethereum/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 9031:9030
      - 9131:9130
    volumes:
      - ${DIR}/mainnet/bb_eth:/opt/coins/blockbook/ethereum/data
    networks:
      infura:
        ipv4_address: 10.2.0.112

  bb_bsc:
    container_name: bb_bsc_mainnet
    restart: unless-stopped
    build: ../../blockbooks/bsc/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9032:9030
      - 9132:9130
    volumes:
      - ${DIR}/mainnet/bb_bsc:/server/coins/blockbook/bsc/data
    networks:
      infura:
        ipv4_address: 10.2.0.113

networks:
  infura:
    name: infura
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
